config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#root'

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  namespace :api, defaults: {format: :json} do
    resources :poems, only: [:index, :create, :show]
    resources :stanzas, only: [:create]
    resources :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
end

app/views/shared/_form.html.erb
<% user_action = ((source === 'new_session') ? 'Log In' : 'Sign Up') %>
<% url = ((source === 'new_session') ? session_url : users_url)%>

<h2 class='login-header'>The MultiVerse: Possibilities in Poetry</h2>
<div class='login-spacer'>&nbsp;</div>

<form class='login-form' action="<%= url %>" method="post">
  <%= auth_token %>
    <input placeholder='Username' class='login-input' type="text"
      name="user[username]" value="<%= @user.username %>">

    <input placeholder='Password' class='login-input' type="password"
      name="user[password]">

    <input class='login-button' type="submit" value="<%= user_action %>">
</form>
<div class='login-spacer'>&nbsp;</div>
<div class='guest-login-container-1'>
  <%= button_to "Guest Account 1: Log in as Mary Oliver.",
    {controller: "sessions", action: "create",
      user: {username: "mary0liver", password: "thesummerdayoliver"}
    },
    {class: 'guest-login-button'}
  %>
</div>
<div class='guest-login-container-2'>
  <%= button_to "Guest Account 2: Log in as Billy Collins.",
    {controller: "sessions", action: "create",
      user: {username: "billy_collins", password: "aimlesslovecollins"}
    },
    {class: 'guest-login-button'}
  %>
</div>
<div class='login-spacer'>&nbsp;</div>